<?php

/** 
 * implementation of hook_menu
*/
function erictest_menu() {

  $items = array();
  // Add a Downloads tab
  $items['civitabs/%user/grades/json'] = array(
    'access callback' => true,
    'page callback' => 'erictest_downloads_json',
    'delivery callback' => 'drupal_json_output',
    'page arguments' => array(1),
  );
  return $items;
}


function erictest_downloads_json($contactID) {
  civicrm_initialize();
  $uid = CRM_Core_BAO_UFMatch::getUFId($contactID);
  $content = views_embed_view('civicrm_tabs', 'page_2', $uid);
  CRM_Core_Page_AJAX::returnJsonResponse($content);
}

/**
 * Add an extra tab to civicrm contact
 * @todo: implement hook_civicrm_tabset because tabs is deprecated
 */
function erictest_civicrm_tabs( &$tabs, $contactID ) {
  $uid = CRM_Core_BAO_UFMatch::getUFId($contactID);

  $url = CRM_Utils_System::url('civitabs/'. $uid . '/grades/json');
  $result = views_get_view_result('civicrm_tabs', 'page_2', $uid);
  $count = count($result);
  $tabs[] = array(
    'id' => 'downloads',
    'url' => $url,
    'title' => ts('Grades'),
    'weight' => 300,
    'count' => $count,
  );
};

